
GAME_WIDTH = 1000
GAME_HEIGHT = 800
PLAYER_WIDTH = 40
PLAYER_HEIGHT = 60
PLAYER_VEL = 8
ENEMIE_WIDTH = 15
ENEMIE_HEIGHT = 30
ENEMIE_VEL = 5
BALL_VEL = 15

FONT_IMAGE = "images/bg.jpeg"

GUN_SONG_PATH = "songs/gun.mp3"
GRENADE_SONG_PATH = "songs/grenade.mp3"