from pathlib import Path

WIDTH = 1000
HEIGHT = 800
PLAYER_WIDTH = 40
PLAYER_HEIGHT = 60
PLAYER_VEL = 8
STAR_WIDTH = 15
STAR_HEIGHT = 30
STAR_VEL = 5
BALL_VEL = 15

BALL_SONG = Path("./songs/ball.mp3")